config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products, only: [:index, :show]
  resource :carts, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :payments
  post "/payments/:id" => "payments#show"
  post "/hook" => "payments#hook"
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :title, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :payments
  belongs_to :user
  validates :order_at, :status, presence: true
  has_one :payment
  def total_price
    order_items.collect { |item| item.valid? ? (item.quantity*item.product.price) : 0 }.sum
  end

  def total_ammount
    order_items.collect { |item| item.valid? ? (item.quantity) : 0 }.sum
  end
  private
    def set_order_status
      self.status = 1
    end

    def update_total
      self.total = total_price
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/order_transaction.rb
class OrderTransaction < ActiveRecord::Base
    belongs_to :order
    serialize :params
  
    def response=(response)
      self.success       = response.success?
      self.authorization = response.authorization
      self.message       = response.message
      self.params        = response.params
    rescue ActiveMerchant::ActiveMerchantError => e
      self.success       = false
      self.authorization = nil
      self.message       = e.message
      self.params        = {}
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order

  def paypal_url(return_path, notify_path)
    values = {
        business: "soaptavish1993-facilitator@gmail.com",
        cmd: "_xclick",
        upload: 1,
        return: return_path,
        invoice: id,
        amount: order.total_price,
        item_name: 'Example order',
        item_number: order.id,
        quantity: 1,
        notify_url: notify_path
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

end

app/models/product.rb
class Product < ApplicationRecord
    max_paginates_per 10
    belongs_to :category
    validates :title, :price, :description, :post_at, presence: true
    validates_numericality_of :price, greater_than: 0
 
    scope :category, -> (category) { where category: category}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery with: :exception
    helper_method :current_order

    def current_order
        if session[:order_id].present?
            Order.where(id: session[:order_id]).first
        else
            Order.new(user: current_user, status: 1, order_at: Time.new)
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @order = current_order
        @payment = Payment.new
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    if @order.save
      session[:order_id] = @order.id
    else
      # iplement flash message
    end
  end
  def update
    @order = current_order
    @order_item = @order.order_items.where(id: params[:id]).first
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
    redirect_to carts_path
  end
  def destroy
    @order = current_order
    @order_item = @order.order_items.where(id: params[:id]).first
    @order_item.destroy
    @order_items = @order.order_items
    redirect_to carts_path
  end
  private
    def order_item_params
        params.require(:order_item).permit(:quantity, :product_id)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show]
  protect_from_forgery except: [:hook]
  def index
    @payments = Payment.all.order(:id).page params[:page]
  end

  def new
  end

  def show
  end

  def create
    @payment = Payment.new(payment_params)
    if @payment.save
      redirect_to @payment.paypal_url(payment_url(@payment), 'https://23ea9538.ngrok.io/hook')
    else
      render :new
    end
  end


  def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]

    if status == "Completed"
      @payment = Payment.where(id: params[:invoice]).first
      @payment.update_attributes!(status: status, purchased_at: Time.now)
    end
    render nothing: true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.where(id: params[:id]).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:order_id, :full_name, :company, :email, :telephone)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        if params[:category]
            @products = Product.where(category: params[:category]).order(:post_at).page params[:page]
          else
            @products = Product.order(:post_at).page params[:page]
        end
        @categories = Category.all
        @order_item = current_order.order_items.new
    end

    def show
        @product = Product.where(id: params[:id]).first
        @order_item = current_order.order_items.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_messages.html.slim
- if flash.present?
  #flash
    script
      - if flash[:success]
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
      - if flash[:info]
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
      - if flash[:danger]
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product \'#{order_item.product.name}\' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

app/views/carts/_cart_row.html.slim
.row
  .col-12
    .table-responsive
      table.table.table-striped
        thead
          tr
            th[scope="col"]

            th[scope="col"]
              | Product
            th.text-center[scope="col"]
              | Unit Price
            th[scope="col"]
            th

        tbody
          - order.order_items.each do |order_item|
            tr
              = link_to product_path(order_item.product) do
                td
                  img_tag(order_item.product.image_url, height='50px', width='50px')

              td
                = order_item.product.title
              td.text-right
                | $
                = order_item.product.price
                |  x 
              td
                = form_for(order_item) do |f|
                  .row
                    .col-xs-4
                      = f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1
                      = f.hidden_field :product_id, value: order_item.product.id
                    .col-xs-8.text-right
                      .btn-group
                        = f.submit "Update", class: "btn btn-primary"
                        = link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.title}' from your cart?" }, method: :delete, class: "btn btn-danger" }
          tr
            td
            td
            td
            td
              strong
                | Total
            td.text-right
              strong
                | $
                = order.total_price
  .col.mb-2
    .row
      .col-sm-12.col-md-6
        = link_to "Continue Shopping", products_path, class: "btn btn-block btn-light"
      .col-sm-12.col-md-6.text-right
        = form_for @payment, html: { class: "basic-grey" } do |f|
          = f.hidden_field :order_id, value: order.id
          = f.submit "Checkout", class: "btn btn-block btn-success text-uppercase"

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render partial: 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/_shopping_cart.html.slim
- if !@order_item.nil? && @order_item.errors.any?
  .alert.alert-danger
    ul
      - @order_item.errors.full_messages.each do |msg|
        li
          = msg
- if @order.order_items.size == 0
  p.text-center
    |  There are no items in your shopping cart. Please 
    = link_to "go back", root_path
    |  and add some items to your cart. 
- else
  = render partial: 'carts/cart_row', locals: { order: @order }

app/views/carts/show.html.slim
.shopping-cart
  = render "shopping_cart"

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.total_price} )", carts_path, class: "btn btn-link" %>

app/views/layouts/_cart_text.html.slim
= link_to carts_path, class: "btn btn-success btn-sm ml-3" do
    | Cart
    span.badge.badge-light
      = current_order.total_ammount.to_s

app/views/layouts/_payment_text.html.slim
= link_to payments_path, class: "btn btn-success btn-sm ml-3" do
    | Payment history

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CommercialProj
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
      .container
        = link_to 'Simple Ecommerce', products_path, class: 'navbar-brand'
        button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
          - if user_signed_in?      
            form.form-inline.my-2.my-lg-0
              .input-group.input-group-sm
                .input-group-append
                  button.btn.btn-secondary.btn-number[type="button"]
              h1.cart-text
                = render partial: 'layouts/cart_text'
              h1.payment_text
                = render partial: 'layouts/payment_text'
              = link_to 'Profile', edit_user_registration_path, method: :get, class: 'btn-success btn btn-success btn-sm ml-3'
              = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'ml-3'
          - else
            = link_to 'Login', new_user_session_path, class: 'btn-success btn btn-success btn-sm ml-3'
    .container[style="margin-top:100px; margin-bottom: 100px"]
      = yield

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/payments/failure.html.slim
FAILURE

app/views/payments/index.html.slim
= paginate @payments
table.table
  thead
    tr
      th.col
        |#
      th.col
        |Purchased at
      th.col
        |Order id
      th.col
        |Status
      th.col
        |
  tbody
    - @payments.each do |payment|
      tr
        td
          = payment.id
        td
          = payment.purchased_at
        td
          = payment.order_id
        td
          = payment.status
= paginate @payments

app/views/payments/new.html.slim
section#course-content
  section#ruby
    section.detailed-syllabus
      .wrapper-inside
        = form_for @payment, html: { class: "basic-grey" } do |f|
          - if @payment.errors.any?
            #error_explanation
              h2
                = pluralize(@payment.errors.count, "error")
                |  prohibited this registration from being saved: 
              ul
                - @payment.errors.full_messages.each do |message|
                  li
                    = message
          .field
            = f.hidden_field :order_id, value: @order.id
          .field
            = f.label :full_name
            = f.text_field :full_name
          .field
            = f.label :company
            = f.text_field :company
          .field
            = f.label :email
            = f.text_field :email
          .field
            = f.label :telephone
            = f.text_field :telephone
          .actions
            = f.submit "Registration Payment", class: "btn", style: "color: white;background: rgb(242, 118, 73);"

app/views/payments/show.html.slim
section#course-content
  section#ruby
    section.detailed-syllabus
      .wrapper-inside
        h3.title
          | Payment invoice
      .columns.clearfix
        .left[style="padding-left:100px;"]
          p
            strong
              | Price:
            |  $#{@payment.order.total_price}
          p
            strong
              | Payment status:
            = @payment.status
          p
            strong
              | Payment date:
            = @payment.purchased_at

app/views/payments/success.html.slim
SUCCESS!

app/views/products/index.html.slim
main[role="main"]
  .dropdown
    button.btn.btn-secondary.dropdown-toggle[type='button', data-toggle='dropdown']
      | Category
    .dropdown-menu[aria-labelledby='dropdownMenuButton']
      - @categories.each do |category|
        a.dropdown-item
          = link_to category.title, products_path(category: category)
          
  = paginate @products
  .album.py-5.bg-light
    .container
      .row
        - @products.each do |product|
          .col-md-4
            .card.mb-4.box-shadow
              = link_to product_path(product) do
                = image_tag product.image_url, class: 'card-img-top', alt: 'Card image cap'
              .card-body
                h3
                  = product.title
                button.btn.btn-sm.btn-outline-secondary[type="button"]
                  = link_to product_path(product) do
                    |  Detail 
                small.text-muted
                  = product.post_at.utc.strftime('%m/%d/%Y %H:%M %p')
                h6
                  = product.category.title
                p.card-text
                  = product.description
                .d-flex.justify-content-between.align-items-center
                  = form_for(@order_item, remote: true)  do |f|
                    = number_to_currency product.price
                    .input-group
                      = f.number_field :quantity, value: 1, class: "form-control", min: 1
                      .input-group-btn
                        = f.hidden_field :product_id, value: product.id
                        = f.submit "Add to Cart", class: "btn btn-primary"
  = paginate @products

app/views/products/show.html.slim
.container
  .row
    .col-lg-9
      .card.mt-4
        = image_tag @product.image_url, class: 'card-img-top', alt: 'Card image cap'
        .card-body
          h3.card-title
            = @product.title
          = form_for(@order_item, remote: true)  do |f|
            = number_to_currency @product.price
            .input-group
              = f.number_field :quantity, value: 1, class: "form-control", min: 1
              .input-group-btn
                = f.hidden_field :product_id, value: @product.id
                = f.submit "Add to Cart", class: "btn btn-primary"
          h4
            | Price: $
            = @product.price
          p.card-text
            = @product.description
          span.text-warning
            | ★ ★ ★ ★ ☆
          |  4.0 stars 